### ISSUE TITLE
cannot start my previous instance

### ISSUE THREAD

**Issue by luojijiaren** [open-datastudio/jupyter#14]
![image](https://user-images.githubusercontent.com/18145176/93412804-bf607d80-f852-11ea-8d00-cd2b384217da.png)
I tried to start my previous instance, but no response when click the "start". I guess it's because my coupon expired. Could you add some tips/clue like "please add coupon or set up credit card" here?

**Comment by Leemoonsoo** [comment]
Thanks for reporting the problem. You're rights. web console does not print any message in that case. We'll address that.

But when I check your coupon, I can see 2 coupons, one expired, another not yet expired. Is it correct?
(let me extend your coupon as well)

**Comment by luojijiaren** [comment]
I only has one coupon (expired one) before I added my credit card there. After I added my credit card, I got a new coupon (not yet expired one) LOL. Thanks for extending my coupon

**Comment by Leemoonsoo** [comment]
Now, the web console is patched to show some error message in this case.
I'm closing this issue. Thank you again @luojijiaren for reporting the problem.
